---
replicaCount: 1
image:
  repository: dhananjaylakkawar/heroku-alike
  pullPolicy: IfNotPresent
  tag: "c9ca99e"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
  hosts:
    - host: secondmyapp.djlakkawar.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: myapp-tls
      hosts:
        - secondmyapp.djlakkawar.cloud
